<?php
// This file was automatically generated by the GamePanelX Pro installer
error_reporting(E_ERROR);
$config['sql_host']  = 'localhost';
$config['sql_user']  = 'root';
$config['sql_pass']  = 'usbw';
$config['sql_db']  = 'tgadmin';
$config['encrypt_key']  = 'b19IPbRMGbxbraDIZd3nBUKKJLDHOt4cs42ucM3wand5cnQfL2kGZ0YEgD5EARQU';
$config['api_key']  = 'wZpz5kLOyXhFarrazndpHut29A8oxOfeqBwUBNPNh6Us9UZpoVGrBjGC4HVG5XXWO7FFG0EAqd2fLzotJ4XA4LYcasrA9s8NKi9GB5VzerPNu9tL5EdMoUO802P10r7';
?>
